### ISSUE TITLE
How to do you proxy a URL that also requires arguments?

### ISSUE THREAD

**Issue by ghost** [HackerYou/json-proxy#24]
I am using this proxy by using the hosted link as so:
`http://proxy.hackeryou.com/?reqUrl=http://example.com`

This code works, however, the specific website I am using ALSO has arguments it must take, and the hosted website thinks that when I add multiple arguments, the new arguments are actually for the proxy itself and not the website I am trying to proxy.

`http://proxy.hackeryou.com/?reqUrl=http://example.com?getPage=1&doCache=false`
How do I create a solution to this?

**Comment by Rchristiani** [comment]
Hi,

That is what the params key is for. If you are using something like jQuery you can pass the data like this:

```js
$.ajax({
	url: 'http://proxy.hackeryou.com',
	dataType: 'json',
	method:'GET',
	data: {
		reqUrl: 'http://example.com',
		params: {
			getPage: 1,
                        doCache: false
		}
	}
}).then(function(res) {
	...
});
```

If you need to just write the request out by hand, you can do this. 

```bash
http://proxy.hackeryou.com/?reqUrl=http://example.com&params[getPage]=1&params[doCache]=false
```

Hope that helps.

**Comment by ghost** [comment]
Thank you so much! This is just what I needed.
